#!/usr/bin/env bash

arcs-reduce-nxs-using-mantid -nxs=arcs-sim.nxs --ei_guess=117 --qaxis=0,13,0.1 
arcs-extract-iqe-from-nxs iqe.nxs iqe.h5
python -c "import histogram.hdf as hh; iqe=hh.load('iqe.h5'); ie=iqe[(3,9), ()].sum('Q'); hh.dump(ie, 'ie-Q3,9.h5')"
