#!/usr/bin/env python
import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')

def main():
    from mcvine.applications.InstrumentBuilder import build
    components = ['source', 'monitor']
    App = build(components)
    app = App('analyze-sqe')
    app.run()
    return

if __name__ == '__main__': main()

# This application was created by the following command:
# $ mcvine-create-instrument-simulation-application -name=analyze-sqe -components=source,monitor

