#!/usr/bin/env bash

python run.py \
    -ncount=1e6 \
    -nodes=2 \
    -Ei=687.834 \
    -E_Q=0.522*Q*Q \
    -S_Q=1. \
    -sigma_Q=Q/2. \
    -Qmin=0. \
    -Qmax=28. \
    -Qstep=0.1 \
    -Emin=-50. \
    -Emax=500. \
    -Estep=1. \
    -mod2sample=../mod2sample \

