#!/usr/bin/env bash

python run.py \
    -ncount=4e7 \
    -nodes=8 \
    -Ei=687 \
    -E_Q=0.522*Q*Q \
    -S_Q=1. \
    -sigma_Q=0.94*Q \
    -Qmin=0. \
    -Qmax=28. \
    -Qstep=0.1 \
    -Emin=-50. \
    -Emax=500. \
    -Estep=1. \
    -mod2sample=../mod2sample \

