#!/usr/bin/env bash

mcvine-convert-mcstas-instrument --input=hyspec_moderator2sample.instr
./config-hyspec_moderator2sample
mv hyspec_moderator2sample ../applications/
mv config-hyspec_moderator2sample ../applications/
mv hyspec_moderator2sample.pml ../etc/hyspec_moderator2sample