#!/usr/bin/env bash

rm -rf out-check-iqe/ ; mcvine-check-iqe -source.path=out/scattered-neutrons  -monitor.Ei=117 -monitor.Emin=-95 -monitor.Emax=95 -monitor.nE=190 -monitor.Qmin=0 -monitor.Qmax=13 -monitor.nQ=30 --ncount=1e7 --buffer_size=1000000

PlotHist.py out-check-iqe/iqe_monitor.h5 

python -c "import histogram.hdf as hh; iqe = hh.load('out-check-iqe/iqe_monitor.h5'); iq = iqe.sum('energy'); hh.dump(iq, 'iq-quick.h5'); ie = iqe.sum('Q'); hh.dump(ie, 'ie-quick.h5')"

PlotHist.py iq-quick.h5

PlotHist.py ie-quick.h5
